### ISSUE TITLE
Failing `wasip1` build after upgrade to cc-1.0.100

### ISSUE THREAD

**Issue by Niederb** [rust-lang/cc-rs#1109]
I have a failing build for `wasip1` after one of my transitive dependencies upgraded `cc` to `v1.0.100`
```
error occurred: Environment variable WASI_SYSROOT not defined. Download sysroot from github & setup environment variable WASI_SYSROOT targetting the folder.
```
(See https://github.com/scs/substrate-api-client/actions/runs/9671307108/job/26681692693 for the failing build)
This seems to be caused by this commit: https://github.com/rust-lang/cc-rs/commit/6a6107a26f3290fed3487f436249f4f5c6d4993d

I'm not quite sure how to fix this. So far we relied on a standard Github runner for our builds and no additional setup for wasi was needed.

**Comment by NobodyXu** [comment]
cc @antaalt can you help me with this issue please?

**Comment by antaalt** [comment]
I am curious as to how you were building to WASI without a particular setup, for the fix of the build, you can download WASI sysroot from [WASI SDK GitHub release pages](https://github.com/WebAssembly/wasi-sdk/releases) and setup the WASI_SYSROOT targeting the folder. You will probably still get issues as there is also an [issue](https://github.com/rust-lang/cc-rs/pull/1105) that need to be fixed with targets

**Comment by NobodyXu** [comment]
Hello @Niederb can you try cc 1.0.102 to see if it fixed your issue?

**Comment by NobodyXu** [comment]
Ok I think we'd need to make the `WASI_SYSROOT` optional, since clang on Linux seems to come with wasi libraries required.

**Comment by Niederb** [comment]
Just to confirm: cc 1.0.103 fixed the issue for me 👍
