### ISSUE TITLE
Wasm32-unknown-unknown does not need SYS_ROOT override

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/cc-rs#1126]
#1114 conflates wasm with wasi targets. While wasi targets should change the sysroot to the wasi-sdk-provided one, the non-wasi target `wasm32-unknown-unknown` should probably keep the default sysroot.

**Comment by madsmtm** [comment]
Things also changed a bit in https://github.com/rust-lang/cc-rs/pull/1225, we should be using `target.os == "wasi"` or `target.arch == "wasm32" || target.arch == "wasm64"` depending on what the desired condition is.

**Comment by madsmtm** [comment]
Reviewing all the places where `wasm` or `wasi` is mentioned:
1. Uses WASI_SYSROOT, seems like it is correct to use `target.os`:
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L1406-L1415
2. Might need `target.arch`, 
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L1996-L2011
3. Might need `target.arch` for `-fno-exceptions` and `-pthread`?
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L2012-L2027
4. Preferring Clang as the compiler might need to be done for `target.arch` instead?
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L2707-L2712
5. The standard C++ library might need `target.arch`? Though might also be correct to use `target.os`
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L2936-L2971
6. Probably need to also check `wasm64` when finding archiver?
    https://github.com/rust-lang/cc-rs/blob/2050013e69bc07e275a65583dd26e8905dfdff73/src/lib.rs#L3097-L3114

But ultimately, I am unsure of all of these, which is why I haven't pursued it myself.

@daxpedda, do you know which of these places it would be correct to use `target.os == "wasi"`, and which ones it'd be correct to use `matches!(target.arch, "wasm32" | "wasm64")`?

**Comment by daxpedda** [comment]
> CC [@daxpedda](https://github.com/daxpedda), do you know which of these places it would be correct to use `target.os == "wasi"`, and which ones it'd be correct to use `matches!(target.arch, "wasm32" | "wasm64")`?

No, unfortunately not.

But while I'm here, I should mention that `target_family == "wasm" && target_os == "unknown"` might be more accurate to describe `wasm32-unknown-unknown` and `wasm64-unknown-unknown`. Because `wasm32-unknown-emscripten` would be covered with `target.arch == "wasm32" || target.arch == "wasm64"` as well. Emscripten is better covered with `target_os == "emscripten"`.

On that note, I don't know what a sysroot for `wasm32-unknown-unknown` for C/C++ would represent, so maybe you are actually trying to target Emscripten here? Just speculating though, I'm clueless about the C/C++ toolchain surrounding Wasm.

**Comment by madsmtm** [comment]
> No, unfortunately not.

Fair, thanks for the answer anyhow!

**Comment by NobodyXu** [comment]
For 1, I think you are right.

For 3, I think the code we actually trying to detect wasip1-thread
