### ISSUE TITLE
Support for MSVC -MTd and -MDd

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cc-rs#1230]
[The CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) lists additional debug variants
for these MSVC flags, but [as far as I can tell](https://github.com/rust-lang/cc-rs/blob/338e434e74262a4de7c3bfca84c087a248bd0c42/src/lib.rs#L1942-L1951), the cc crate doesn't support the debug variants.

**Comment by retep998** [comment]
It doesn't support it because the rest of the rust ecosystem doesn't either. Fixing this would require a much more coordinated effort across multiple repos, and still would have an ugly transition period.

**Comment by NobodyXu** [comment]
Yeah I tried it and have to revert it, as it breaks rust compilation

**Comment by ChrisDenton** [comment]
The core issue is that rustc doesn't support this so there's no way for `cc` to know if this was wanted. `cc` could have a function for overriding the CRT libraries if someone really knows what they're doing but it is a bit of a footgun because it's super important that everything uses the same C runtime libraries.

To recap, this is the current state of affairs:

|C/C++|rustc|Native libs|
|--|--|--|
|`/MT`|`+crt-static`|libcmt, libvcruntime, libucrt|
|`/MTd`|❌|libcmtd, libvcruntimed, libucrtd|
|`/MD`|`-crt-static`|msvcrt, vcruntime, ucrt|
|`/MDd`|❌|msvcrtd, vcruntimed, ucrtd|

So compiling using rustc only has two options. You can override Rust's choices by using a linker argument. E.g. `/NODEFAULTLIB:msvcrt /DEFAULTLIB:msvcrtd` to use the debug libraries. But you need some way to coordinate that choice with everyone and everything else.

**Comment by NobodyXu** [comment]
> So compiling using rustc only has two options. You can override Rust's choices by using a linker argument. E.g. /NODEFAULTLIB:msvcrt /DEFAULTLIB:msvcrtd to use the debug libraries.

If it is possible to override using a linker argument, then maybe we can add a new flag/env to use the debug version of msvc runtime?

**Comment by retep998** [comment]
Related issue: https://github.com/rust-lang/rust/issues/39016

**Comment by ChrisDenton** [comment]
An environment variable might work to keep it consistent across the whole build.

We also need to keep in mind a future where rustc hopefully gains support for the debug CRTs. Then we'd just need to query it the same way we do `crt-static`.

**Comment by crumblingstatue** [comment]
Thank you for the information everyone!
I guess in my case I'll just have to force my CMake dependency to build without debug support.

**Comment by MeFisto94** [comment]
Note: With the following contents in `.cargo/config.toml` and `build.rs` one can already opt into using MTd/MDd:
```toml
[build]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
CFLAGS = "/MTd"
CXXFLAGS = "/MTd"
```

```rs
// Don't link the default CRT
    println!("cargo::rustc-link-arg=/nodefaultlib:msvcrt");
    println!("cargo::rustc-link-arg=/nodefaultlib:libcmtd");
    println!("cargo::rustc-link-arg=/nodefaultlib:libcmt");
    // Link the debug CRT instead
    println!("cargo::rustc-link-arg=/defaultlib:msvcrtd");
```
This will, however, issue a warning from MSVC because cc already passed `/MT` and `/MTd` takes precedence.

I wonder if it would make sense to emit a warning in cc, though, when `.debug(true)` is passed (though technically this would probably affect far too many builds even when using the debug MSCRT may not even be desired)

**Comment by NobodyXu** [comment]
Hmm yeah we could do that, but isn't there already warning from msvc?

Sorry maybe I'm missing something

**Comment by ChrisDenton** [comment]
I do think the best approach would be to have an environment variable that tells `cc-rs` which `/M*` flag to use (or maybe just to suppress emitting it entirely). We could additionally (or alternatively) make a best effort at suppressing it if there's a relevant flag in `CFLAGS`, `CXXFLAGS`, `CL` or `_CL_`.  But that may not be robust.

**Comment by NobodyXu** [comment]
Yeah...that might be too many env var though

We already got many of them so I'm reluctant to add more

**Comment by ChrisDenton** [comment]
Well I do think it would need to be derived from the environment in some way. Because it has to be the same across all uses of cc-rs. Ideally rustc would have a feature for this but, lacking that, environment variables seem to be the only way to coordinate global settings.

**Comment by NobodyXu** [comment]
Maybe have a `CC_MSVC_STATIC` flag?

**Comment by ChrisDenton** [comment]
Something like that would make sense to me. Though I'm not sure about that exact name since the important thing here is whether or not to use the debug runtime libraries (for both static and dynamic CRTs). Maybe `CC_MSVC_DEBUG`.

**Comment by NobodyXu** [comment]
Maybe we should just have `CC_MSRV_FLAVOR` instead of two variables?

**Comment by retep998** [comment]
I still think we should just use the same system as we do for choosing between dynamic and static CRT. Unless someone can provide a convincing argument for why that *shouldn't* be used, I'd much rather us stick to the existing system and simply extend it to also allow selecting debug vs release.

Similar to `-C target-feature=+crt-static` we should have `-C target-feature=+crt-debug`.

**Comment by ChrisDenton** [comment]
That would be better, yes. But unfortunately cc-rs can only work with what rustc currently gives us.

**Comment by retep998** [comment]
So what you're saying is I'm going to have to create a PR to rust to add `+crt-debug` because nobody else decided to do it in the **8** years since I directly suggested we do that.

**Comment by ChrisDenton** [comment]
If you're willing to do that then it would be helpful, yes.
