### ISSUE TITLE
Compiling from `msbuild` incorrectly uses target build tools for build scripts

### ISSUE THREAD

**Issue by dlon** [rust-lang/cc-rs#1308]
The problem arises when running `cargo build` from within a VS project and targeting something other than the native arch (e.g., using `msbuild.exe myproj.sln /p:Platform=otherarch`). When cargo builds a build script, it uses the target linker (added to `PATH` by Visual Studio) instead of the host linker, which naturally fails.

This is a problem as of Rust 1.83 due to the following fix: https://github.com/rust-lang/cc-rs/pull/1201. That PR also contains some discussion about this issue.

**Comment by dlon** [comment]
@NobodyXu @ChrisDenton Would you accept a PR based on your suggestion of parsing the output of `cl.exe`? :)

The odd thing about it is that the msbuild tools will be used for the native architecture build scripts, but not otherwise. That's a bit counter-intuitive, perhaps.

**Comment by NobodyXu** [comment]
Yes I'm willing to review and merge it

**Comment by ChrisDenton** [comment]
Looking at the code, for Visual Studio proper (e.g. after vcvars.bat) we use `VSCMD_ARG_TGT_ARCH` to verify the environment is set up for the target and then `VSINSTALLDIR` to find the path to Visual Studio, which we then use to set the toolchain to the right target:

https://github.com/rust-lang/cc-rs/blob/5daf14e96f28bfa634c135c87a953afdbefeb63e/src/windows/find_tools.rs#L390-L393

https://github.com/rust-lang/cc-rs/blob/5daf14e96f28bfa634c135c87a953afdbefeb63e/src/windows/find_tools.rs#L358-L370

MSBuild does not set either of those nor does it set anything equivalent. For `VSCMD_ARG_TGT_ARCH` we can instead parse the header of `cl.exe`. For `VSINSTALLDIR` I guess we can instead just `return None` from `find_msvc_environment` so that it'll fallback to finding the latest matching tools.

**Comment by NobodyXu** [comment]
> For VSCMD_ARG_TGT_ARCH we can instead parse the header of cl.exe.

Hmmm how hard would it be?
Would it be portable?

> For VSINSTALLDIR I guess in the case where there's a target mismatch we can instead just return None from find_msvc_environment so that it'll fallback to finding the latest matching tools.

👍

**Comment by ChrisDenton** [comment]
> Hmmm how hard would it be?

I meant the thing I mentioned earlier about parsing the line that appears at the top of stderr from `cl.exe` (which `cl.exe` actually calls the "logo").

**Comment by NobodyXu** [comment]
Thanks that's quite easy.

**Comment by dlon** [comment]
I've now opened #1310. Thank you both for the help!

**Comment by jschwe** [comment]
Does this issue and the related fix also affect the build of proc macros? And in which Rust version will the fix be available?

Background: I received [an issue in corrosion](https://github.com/corrosion-rs/corrosion/issues/599), that when using Visual Studio as the Generator proc macros fail to link as of Rust 1.83 when cross-compiling, unless VSTEL_MSBuildProjectFullPath is unset - which sounds very similar to this issue.

**Comment by ChrisDenton** [comment]
Proc macros, like build scripts, run using the host compiler so it's possible for them to be affected by this, yes.

The fix will be available in the next Rust release (scheduled for Thursday 09 January). The `beta` channel could be used to try it early. As we're close to a release it should be mostly release ready (but still, there might be last minute backports that have yet to be applied).

**Comment by madsmtm** [comment]
I see you've gotten an answer that [this isn't fixed on nightly Rust](https://github.com/corrosion-rs/corrosion/issues/599#issuecomment-2569193963), so might be a different issue.

**Comment by sevenc-nanashi** [comment]
fyi: this isn't fixed on nightly Rust

I haven't updated my nightly in that time.
I updated my nightly and the issue was solved, sorry!
