### ISSUE TITLE
Feature request: support setting asm-specific flags

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/cc-rs#751]
Background: clang fails with an error if you pass asm options when compiling a non-asm input. For example:
```console
$ clang -c foo.S -Wa,-defsym,abc=0
(no error!)

$ clang -c foo.c -Wa,-defsym,abc=0
error: unknown argument: '-defsym'
```

It would be helpful to have a `Build::asm_flag` method for adding flags specific to compiling assembly. The flags passed in this way would only be added to the command for `.S`/`.asm` files.

**Comment by thomcc** [comment]
Patch welcome.

**Comment by dot-asm** [comment]
Formally speaking, one could have used `flag_if_supported("-no-integrated-as")` in this case. And one can wonder if it would be generally more appropriate. Indeed, since the suggestion is to pass the option to multiple files, it implies that the symbol definition is intended to be global. In which case C is formally entitled to refer to it too :-)
