### ISSUE TITLE
Surprised to find NDEBUG not implicitly defined in release builds

### ISSUE THREAD

**Issue by mlabbe** [rust-lang/cc-rs#771]
`cc-rs` never defines `NDEBUG` and I'm surprised to find this!

Compiling with `cargo build --release` sets `DEBUG=Some(false)` environment variable as expected, and passes the correct `OPT_LEVEL` to the compiler.  These are implicit things that happen in this crate.

However, it is common with release-style builds to set the standard `NDEBUG` environment variable which is used to generate no-op assert() macros at compile time.  In the case of this crate, `NDEBUG` is not set (and looks to never be set) by default.  Therefore, all downstream projects that build in release mode using `cc-rs` that do not explicitly define `NDEBUG` have asserts enabled in release mode.

This report is not about changing this default behaviour -- I think in terms of user expectations that ship has sailed, and making the change may bring about unexpected results.  If someone is depending on C code that runs an assert that has a necessary side effect, changing that would subtly break the code when the user updated their `cc-rs` dependency!

Instead, this report is about the surprising nature of finding that all asserts are enabled in release builds, and that NDEBUG is not defined.  At the very least, I believe this should be documented. 

Forcing users to make an explicit choice about how to handle asserts in C code called by Rust is a reasonable discussion that may result in changes to cc-rs but is out of scope for this report.

**Comment by thomcc** [comment]
I don't think we're going to set this. Consider:
- Crates that compile C libraries with asserts enabled because they have no other way of exposing a sound API in some cases (some C libraries do not give a way of detecting API misuse).
- Crates that manually control assertions with cargo features. 

Both of these exist and would have behavioral changes or risk UB if we started automatically disabling assertions. It often is fine, but that's not something we're in a position to know about — the code using `cc` should make that call IMO.

---

It's also worth noting that there's nothing we can easily [read from the env](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) if we're in a build script for something with `cfg(debug_assertion)` enabled:

- `DEBUG` is set to indicate that debuginfo should be generated, it's not about assertions.
- `OPT_LEVEL`  is compiler optimization level; also different (opt+assert builds are a thing)
- `CARGO_CFG_DEBUG_ASSERTIONS` looks right but is never actually provided, due to some implementation details of how cargo's `cfg` detection works.
- The best I've found in practice is that assertions should be on if `std::env::var("PROFILE") == "debug"` (yes, `"debug"` even though the profile name is `"dev"`), since unlike the others, it will match the Rust crate at least...

Anyway, that really has no bearing on whether or not we implement this feature (firm no), but take it as a caveat if you try to implement it yourself.

**Comment by thomcc** [comment]
I'm going to close this, but would accept a PR to improve documentation here (so long as it is clear/accurate/etc)

**Comment by mlabbe** [comment]
We definitely agree that implicitly defining NDEBUG by implying the build type from the env would not be wise.  

NDEBUG, while part of the C spec, is only set by compilers when explicitly defined, ie: `clang -DNDEBUG`.  Thus, it falls on the build system and not the compiler.

Given that many build systems (including Visual Studio) define NDEBUG for release configurations by default, many code projects extend the use of NDEBUG to do things beyond check asserts.

I do wonder how many people generate Rust bindings without defining NDEBUG by omission, generating lower performing release builds than they would otherwise intend by enabling things like tracing, etc. since many libraries extend NDEBUG to do things outside of asserts. Once they do this and garner users, it would be tricky and possibly dangerous for them to reconsider for the same reasons we agree it would be bad for  this project to automatically start enabling it.

I agree with you that documentation is needed.  Possibly nudging users to be explicit about their choice to not define NDEBUG when writing new build scripts with a warning would also be helpful.
