### ISSUE TITLE
Build::clone does not behave as expected

### ISSUE THREAD

**Issue by Be-ing** [rust-lang/cc-rs#789]
Build derives Clone, which seems nice but ends up not behaving as expected because most of its data is contained in Arcs. So, cloning a Build, then modifying the cloned value, modifies both the original and the clone. :dizzy_face:

I noticed this when using the [`+whole-archive`](https://doc.rust-lang.org/rustc/command-line-arguments.html#linking-modifiers-whole-archive) link modifier on one Build that I cloned from another which I did *not* want to use `+whole-archive`. When both libraries were linked with `+whole-archive` and files were compiled into both of them, I got duplicate symbol errors when linking.

Clone could be implemented manually to avoid this. Or alternatively, just get rid of the derive macro.

**Comment by thomcc** [comment]
> Build derives Clone, which seems nice but ends up not behaving as expected because most of its data is contained in Arcs.

While there's quite a few `Arc<str>`/`Arc<Path>`/etc, these cannot be your issue:
- These have no interior mutability, which is required to mutate an Arc that has multiple living clones.
- Even if that were wrong (it is not) these are not mutated in any way internally, nor are the
- Those are only in git still -- the current releases of `cc` on crates.io all use `String`/`PathBuf` and not `Arc`.

The fields that are behind `Arc<Mutex<_>>` can be mutated (because of the mutex), but they're all caches which are conceptually idempotent. Specifically `known_flag_support_status`, `env_cache`, and `apple_sdk_root_cache` are find the way they are, since they shouldn't change.

> I noticed this when using the [`+whole-archive`](https://doc.rust-lang.org/rustc/command-line-arguments.html#linking-modifiers-whole-archive) link modifier on one Build that I cloned from another which I did _not_ want to use `+whole-archive`. When both libraries were linked with `+whole-archive` and files were compiled into both of them, I got duplicate symbol errors when linking.

The state you describe is stored in `link_lib_modifiers: Vec<Arc<str>>,` (or `Vec<String>` on the [current release](https://docs.rs/cc/1.0.79/src/cc/lib.rs.html#120)), which is a type that can derive Clone without issues.

I don't fully understand your situation, but I think this is just the behavior you get if you link the same static library twice, regardless of `+whole-archive`.
