### ISSUE TITLE
Specifying "no_default_flags(true)" doesn't actually disable all default flags when compile CUDA code with nvcc

### ISSUE THREAD

**Issue by Jark5455** [rust-lang/cc-rs#864]
Currently, I am trying to compile CUDA code with nvcc in my build script and export it to a .ptx file. The desired compile command is rather simple and looks like this.

```
nvcc -ptx ./cuda/example.cu
```

My build.rs looks like this

```
extern crate cc;

fn main() {
    cc::Build::new()
        .cuda(true)
        .no_default_flags(true)
        .flag("-ptx")
        .file("cuda/example.cu")
        .compile("example.ptx")
}
```

However it appears that even with "no_default_flags" enabled, my compilation command is this:

```
 nvcc -ccbin=c++ -Xcompiler -Wall -Xcompiler -Wextra -ptx -o /home/user/CLionProjects/CudaEx/target/debug/build/CudaEx-82cc37462807794c/out/cuda/example.o -c cuda/example.cu
```

How can I disable ALL default flags?

**Comment by dot-asm** [comment]
The explicit purpose of the cc-rs and the .compile() method in particular is to produce a static library and make arrangements so that it's then passed to rustc for linking into the final executable object. If you want to produce **anything else**, cc-rs is not the tool. Just use `std::process::Command`...

**Comment by David-OConnor** [comment]
`Wextra` appears to not be a valid flag when compiling for Windows. Is it not possible to remove unless skipping `cc`?
